from mcp.server.fastmcp import FastMCP

# Init
mcp = FastMCP("ForgeGeneratedServer")

@mcp.tool()
def example_tool(argument: str) -> str:
    """Description"""
    # The code generated by Hermes will go here.
    return f"Résultat pour {argument}"

if __name__ == "__main__":
    mcp.run()
